delete from public.templates;

insert into public.templates (
  code,
  name,
  category,
  description,
  image_url,
  tag,
  is_active,
  sort_order
)
values
  ('vp-template-wedding-1', 'Elegant Wedding Invitation', 'Wedding', 'Vistaprint wedding invitation template. Common options include vertical wedding cards, premium glossy stock, and 12.7 x 17.8 cm or 15.2 x 22.9 cm sizes.', '/vistaprint/templates/vp-template-wedding-1.jpg', 'Vistaprint', true, 1),
  ('vp-template-wedding-2', 'Floral Wedding Invitation', 'Wedding', 'Vistaprint wedding invitation template with floral styling. Supports final text customisation before print ordering.', '/vistaprint/templates/vp-template-wedding-2.jpg', 'Vistaprint', true, 2),
  ('vp-template-wedding-3', 'Classic Wedding Card', 'Wedding', 'Vistaprint wedding card layout for marriage invitations, available with common flat or folded card selections.', '/vistaprint/templates/vp-template-wedding-3.jpg', 'Premium', true, 3),
  ('vp-template-wedding-4', 'Premium Wedding Card', 'Wedding', 'Vistaprint premium-style wedding card template for final names, venue, date, and message personalisation.', '/vistaprint/templates/vp-template-wedding-4.jpg', 'Premium', true, 4),
  ('vp-template-birthday-1', 'Birthday Party Invitation', 'Birthday', 'Vistaprint birthday invitation template. Common options include 12.7 x 17.8 cm cards, premium glossy stock, and custom party text.', '/vistaprint/templates/vp-template-birthday-1.jpg', 'Vistaprint', true, 5),
  ('vp-template-birthday-2', 'Kids Birthday Invite', 'Birthday', 'Vistaprint birthday invitation design for kids parties with editable celebration details.', '/vistaprint/templates/vp-template-birthday-2.jpg', 'Vistaprint', true, 6),
  ('vp-template-birthday-3', 'Modern Birthday Card', 'Birthday', 'Vistaprint birthday card template for party invites, guest details, and final print-ready customisation.', '/vistaprint/templates/vp-template-birthday-3.jpg', 'New', true, 7),
  ('vp-template-birthday-4', 'Premium Birthday Invite', 'Birthday', 'Vistaprint birthday invitation template with premium card styling and editable text.', '/vistaprint/templates/vp-template-birthday-4.jpg', 'Premium', true, 8),
  ('vp-template-poster-1', 'Event Poster Template', 'Poster', 'Vistaprint poster template for events and announcements. Common poster options include A2 and 16 x 20 inch style selections.', '/vistaprint/templates/vp-template-poster-1.jpg', 'Vistaprint', true, 9),
  ('vp-template-poster-2', 'Business Poster Template', 'Poster', 'Vistaprint poster design for business promotions, offers, and in-store announcements.', '/vistaprint/templates/vp-template-poster-2.jpg', 'Vistaprint', true, 10),
  ('vp-template-poster-3', 'Sale Poster Template', 'Poster', 'Vistaprint poster template for sale campaigns with editable headline and product messaging.', '/vistaprint/templates/vp-template-poster-3.jpg', 'New', true, 11),
  ('vp-template-poster-4', 'Announcement Poster Template', 'Poster', 'Vistaprint poster template for announcements, local promotions, and print-ready notices.', '/vistaprint/templates/vp-template-poster-4.jpg', 'Premium', true, 12);

delete from public.services
where code in (
  'vp-photo-with-frame',
  'vp-premium-photo-frame',
  'vp-acrylic-photo-frame',
  'vp-led-photo-frame'
);

insert into public.services (
  code,
  name,
  description,
  base_price,
  print_price,
  category,
  image_url,
  source_url,
  supplier,
  supplier_label,
  product_details,
  product_options,
  is_active,
  sort_order
)
values
  (
    'premium-retouching',
    'Premium Retouching',
    'Professional photo retouching with polished cleanup, tone correction, and final soft-copy delivery.',
    49,
    0,
    'retouching',
    '/services/premium-retouching.jpg',
    null,
    null,
    null,
    array['Rs. 49', 'Soft copy', 'All customisations included'],
    '[{"key":"delivery_package","label":"Delivery package","type":"select","values":["Soft Copy (All customisations)"],"required":true}]'::jsonb,
    true,
    1
  ),
  (
    'digital-sketch',
    'Digital Sketch',
    'Digital sketch artwork with colour or black and white output options, delivered as soft copy or framed output.',
    49,
    0,
    'sketch',
    '/services/digital-sketch.jpg',
    null,
    null,
    null,
    array['Rs. 49 soft copy', 'Rs. 199 standard photo frame', 'Premium Vistaprint frame subject to customisations'],
    '[{"key":"output_package","label":"Output package","type":"select","values":["Soft Copy (All customisations)","Standard Photo Frame (Local) - Rs. 199","Premium Photo Frame (Vistaprint) - quote after final design"],"required":true},{"key":"sketch_style","label":"Sketch style","type":"select","values":["Colour","Black and White"],"required":true},{"key":"frame_size","label":"Frame size","type":"select","values":["No frame","4 x 4 in","4 x 8 in","6 x 6 in","6 x 12 in","8 x 8 in","8.5 x 11 in","10 x 10 in"],"required":true}]'::jsonb,
    true,
    2
  ),
  (
    'custom-sketch',
    'Custom Sketch',
    'Tell us what you want; DK STUDIOS creates the sketch and refines it with you. Frame pricing may vary by customisation.',
    49,
    0,
    'sketch',
    '/services/custom-sketch.jpg',
    null,
    null,
    null,
    array['Rs. 49 soft copy', 'Rs. 199 standard photo frame', 'Premium Vistaprint frame subject to customisations'],
    '[{"key":"output_package","label":"Output package","type":"select","values":["Soft Copy (All customisations)","Standard Photo Frame (Local) - Rs. 199","Premium Photo Frame (Vistaprint) - quote after final design"],"required":true},{"key":"sketch_style","label":"Sketch style","type":"select","values":["Colour","Black and White"],"required":true},{"key":"frame_size","label":"Frame size","type":"select","values":["No frame","4 x 4 in","4 x 8 in","6 x 6 in","6 x 12 in","8 x 8 in","8.5 x 11 in","10 x 10 in"],"required":true}]'::jsonb,
    true,
    3
  ),
  (
    'poster-making',
    'Poster Making',
    'Premium poster layout for events, launches, announcements, and promotions with final soft-copy delivery.',
    49,
    0,
    'design',
    '/services/poster-making.jpg',
    null,
    null,
    null,
    array['Rs. 49', 'Soft copy', 'All customisations included'],
    '[{"key":"poster_size","label":"Poster size","type":"select","values":["Digital poster","A4","A3","A2","16 x 20 in"],"required":true},{"key":"design_status","label":"Design input","type":"select","values":["I will upload final content","DK STUDIOS should prepare layout"],"required":true}]'::jsonb,
    true,
    4
  ),
  (
    'vp-photo-with-frame',
    'Photo With Frame',
    'Vistaprint photo frame from your final photo or design, with black or white frame colour options and multiple sizes.',
    195,
    0,
    'vistaprint_photo_frames',
    '/vistaprint/frames/photo-with-frame.jpg',
    'https://www.vistaprint.in/photo-gifts/photo-with-frame',
    'vistaprint',
    'Powered by Vistaprint',
    array['From Rs. 195', 'Black or white frame', 'Sizes from 4 x 4 in to 10 x 10 in'],
    '[{"key":"quantity","label":"Quantity","type":"select","values":["1","2","5","10"],"required":true},{"key":"size","label":"Size","type":"select","values":["4 x 4 in","4 x 8 in","6 x 6 in","6 x 12 in","8 x 8 in","8.5 x 11 in","10 x 10 in"],"required":true},{"key":"orientation","label":"Orientation","type":"select","values":["Horizontal","Vertical"],"required":true},{"key":"frame_color","label":"Frame color","type":"select","values":["Black","White"],"required":true},{"key":"design_status","label":"Design file","type":"select","values":["I will upload final design","DK STUDIOS should prepare design"],"required":true}]'::jsonb,
    true,
    190
  ),
  (
    'vp-premium-photo-frame',
    'Premium Photo with Frame',
    'Vistaprint premium photo frame for higher-end framed photo output, subject to selected size and customisations.',
    390,
    0,
    'vistaprint_photo_frames',
    '/vistaprint/frames/premium-photo-frame.jpg',
    'https://www.vistaprint.in/photo-gifts/premium-photo-frames',
    'vistaprint',
    'Powered by Vistaprint',
    array['From Rs. 390', 'Black frame', '8 x 8 in and 8.5 x 11 in'],
    '[{"key":"quantity","label":"Quantity","type":"select","values":["1","2","5","10"],"required":true},{"key":"size","label":"Size","type":"select","values":["8 x 8 in","8.5 x 11 in"],"required":true},{"key":"frame_color","label":"Frame color","type":"select","values":["Black"],"required":true},{"key":"design_status","label":"Design file","type":"select","values":["I will upload final design","DK STUDIOS should prepare design"],"required":true}]'::jsonb,
    true,
    191
  ),
  (
    'vp-acrylic-photo-frame',
    'Acrylic Photo Frame',
    'Vistaprint acrylic photo frame with stand, suitable for premium desk or gift presentation.',
    492,
    0,
    'vistaprint_photo_frames',
    '/vistaprint/frames/acrylic-photo-frame.jpg',
    'https://www.vistaprint.in/photo-gifts/acrylic-photo-frame',
    'vistaprint',
    'Powered by Vistaprint',
    array['From Rs. 492', 'Acrylic frame', 'A5 style options'],
    '[{"key":"quantity","label":"Quantity","type":"select","values":["1","2","5","10"],"required":true},{"key":"size","label":"Size","type":"select","values":["A5","A4"],"required":true},{"key":"orientation","label":"Orientation","type":"select","values":["Horizontal","Vertical"],"required":true},{"key":"design_status","label":"Design file","type":"select","values":["I will upload final design","DK STUDIOS should prepare design"],"required":true}]'::jsonb,
    true,
    192
  ),
  (
    'vp-led-photo-frame',
    'LED Photo Frames',
    'Vistaprint LED photo frame for illuminated photo gifts and premium display orders.',
    932,
    0,
    'vistaprint_photo_frames',
    '/vistaprint/frames/led-photo-frame.jpg',
    'https://www.vistaprint.in/photo-gifts/led-photo-frames',
    'vistaprint',
    'Powered by Vistaprint',
    array['From Rs. 932', 'LED frame', 'Premium display'],
    '[{"key":"quantity","label":"Quantity","type":"select","values":["1","2","5","10"],"required":true},{"key":"design_status","label":"Design file","type":"select","values":["I will upload final design","DK STUDIOS should prepare design"],"required":true}]'::jsonb,
    true,
    193
  )
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  base_price = excluded.base_price,
  print_price = excluded.print_price,
  category = excluded.category,
  image_url = excluded.image_url,
  source_url = excluded.source_url,
  supplier = excluded.supplier,
  supplier_label = excluded.supplier_label,
  product_details = excluded.product_details,
  product_options = excluded.product_options,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order;
