alter table public.services
  add column if not exists image_url text,
  add column if not exists source_url text,
  add column if not exists supplier text,
  add column if not exists supplier_label text,
  add column if not exists product_details text[] not null default '{}';

insert into public.services (
  code,
  name,
  description,
  base_price,
  print_price,
  category,
  image_url,
  source_url,
  supplier,
  supplier_label,
  product_details,
  is_active,
  sort_order
)
values
  (
    'vistaprint-personalised-notebooks',
    'Personalised Notebooks',
    'Custom notebooks, journals, writing pads, and photo notebooks ordered from a final design.',
    0,
    0,
    'vistaprint_stationery',
    'https://cms.cloudinary.vpsvc.com/image/upload/c_scale,dpr_auto,f_auto,q_auto:best,t_pdpHeroGallery_Gallery,w_auto/India%20LOB/Stationery%2C%20Letterheads%20and%20Stamps/Notebook_2026/Personalised%20Notebooks/IN_Personalised-notebooks_Hero-image_01',
    'https://www.vistaprint.in/stationery/notebooks/personalised-notebooks',
    'vistaprint',
    'Powered by Vistaprint',
    array['Notebooks', 'Journals', 'Writing pads', 'Photo covers'],
    true,
    101
  ),
  (
    'vistaprint-bill-books',
    'Custom Bill Books',
    'Printed bill books for shops and businesses with logo, text, and uploaded artwork.',
    0,
    0,
    'vistaprint_stationery',
    'https://cms.cloudinary.vpsvc.com/image/upload/c_scale,dpr_auto,f_auto,q_auto:best,t_pdpHeroGallery_Gallery,w_auto/India%20LOB/Stationery%2C%20Letterheads%20and%20Stamps/Custom%20Bill%20Books/IN_Custom-Bill-Books_Hero-image_01',
    'https://www.vistaprint.in/stationery/bill-books',
    'vistaprint',
    'Powered by Vistaprint',
    array['Logo and text', 'Upload design', 'Multiple sizes', '50 sheets per pad'],
    true,
    102
  ),
  (
    'vistaprint-booklets-magazines',
    'Booklets and Magazines',
    'Booklet and magazine-style printing for catalogs, programs, and business stories.',
    0,
    0,
    'vistaprint_magazines',
    'https://cms.cloudinary.vpsvc.com/image/upload/c_scale,dpr_auto,f_auto,q_auto:best,t_pdpHeroGallery_Gallery,w_auto/India%20LOB/Booklets/IN_booklets_002',
    'https://www.vistaprint.in/stationery/booklets',
    'vistaprint',
    'Powered by Vistaprint',
    array['Booklets', 'Magazines', 'Catalogs', 'Multi-page print'],
    true,
    103
  ),
  (
    'vistaprint-wedding-invitations',
    'Wedding Invitation Cards',
    'Personalised wedding, marriage, and shaadi invitation cards from uploaded final artwork.',
    0,
    0,
    'vistaprint_invitations',
    'https://cms.cloudinary.vpsvc.com/image/upload/c_scale,dpr_auto,f_auto,q_auto:best,t_pdpHeroGallery_Gallery,w_auto/India%20LOB/Stationery%2C%20Letterheads%20and%20Stamps/Wedding%20Invitations/IN_Wedding-Invitations_Hero-image_01',
    'https://www.vistaprint.in/stationery/wedding-invitations',
    'vistaprint',
    'Powered by Vistaprint',
    array['Wedding cards', 'Marriage cards', 'Shaadi invites', 'Custom themes'],
    true,
    104
  ),
  (
    'vistaprint-birthday-invitations',
    'Birthday Invitation Cards',
    'Printed birthday party invitations using custom themes, text, and final artwork.',
    0,
    0,
    'vistaprint_invitations',
    'https://cms.cloudinary.vpsvc.com/image/upload/c_scale,dpr_auto,f_auto,q_auto:best,t_pdpHeroGallery_Gallery,w_auto/India%20LOB/Stationery%2C%20Letterheads%20and%20Stamps/Birthday%20Invitation%20Cards/IN_Birthday-Invitation-Cards_Hero-image_01',
    'https://www.vistaprint.in/stationery/birthday-invitation-cards',
    'vistaprint',
    'Powered by Vistaprint',
    array['Birthday cards', 'Party themes', 'Custom text', 'Upload design'],
    true,
    105
  ),
  (
    'vistaprint-stamps',
    'Custom Stamps',
    'All stamp types available through Vistaprint, including self-inking, rubber, pocket, and fabric stamps.',
    0,
    0,
    'vistaprint_stamps',
    'https://cms.cloudinary.vpsvc.com/image/upload/c_scale,dpr_auto,f_auto,w_450/India%20LOB/Stamps/Self%20Inking%20Stamps%20-%20Round%20Rectangle/IN_Self-Inking-Stamps-Round-Rectangle_Overview',
    'https://www.vistaprint.in/stationery/stamps',
    'vistaprint',
    'Powered by Vistaprint',
    array['Self-inking', 'Rubber stamps', 'Pocket stamps', 'Fabric stamps'],
    true,
    106
  ),
  (
    'vistaprint-clothing-bags',
    'Clothing, Caps and Bags',
    'Custom apparel and bags including T-shirts, polos, office shirts, caps, jackets, and bags.',
    0,
    0,
    'vistaprint_clothing_bags',
    'https://cms.cloudinary.vpsvc.com/image/upload/c_scale,dpr_auto,f_auto,w_450/India%20LOB/Clothing%20and%20Bags/Premium%20Polo%20T-Shirts/IN_Premium-Polo-T-Shirts_Overview',
    'https://www.vistaprint.in/clothing-bags',
    'vistaprint',
    'Powered by Vistaprint',
    array['T-shirts', 'Polos', 'Caps', 'Bags'],
    true,
    107
  ),
  (
    'vistaprint-calendars',
    'Custom Calendars',
    'Personalised calendars for gifting, business branding, desk use, walls, posters, and magnetic formats.',
    0,
    0,
    'vistaprint_photo_gifts',
    'https://cms.cloudinary.vpsvc.com/image/upload/c_scale,dpr_auto,f_auto,w_450/India%20LOB/Calendars/2026/Desk%20Calendars/IN_Desk-calendars_Overview',
    'https://www.vistaprint.in/photo-gifts/calendars',
    'vistaprint',
    'Powered by Vistaprint',
    array['Desk calendars', 'Wall calendars', 'Poster calendars', 'Magnet calendars'],
    true,
    108
  ),
  (
    'vistaprint-magnets',
    'Custom Magnets',
    'Printed magnets for gifts, promotions, calendars, vehicles, and magnetic business cards.',
    0,
    0,
    'vistaprint_photo_gifts',
    'https://cms.cloudinary.vpsvc.com/image/upload/c_scale,dpr_auto,f_auto,w_450/India%20LOB/Photo%20Magnets/IN-phot-magnets-tile-overview',
    'https://www.vistaprint.in/photo-gifts/magnets',
    'vistaprint',
    'Powered by Vistaprint',
    array['Fridge magnets', 'Car magnets', 'Magnetic cards', 'Photo magnets'],
    true,
    109
  )
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  base_price = excluded.base_price,
  print_price = excluded.print_price,
  category = excluded.category,
  image_url = excluded.image_url,
  source_url = excluded.source_url,
  supplier = excluded.supplier,
  supplier_label = excluded.supplier_label,
  product_details = excluded.product_details,
  is_active = excluded.is_active,
  sort_order = excluded.sort_order;
